import '../styles/style.css';

import { Syne } from 'next/font/google';
import localFonts from 'next/font/local';

import Header from '@/src/components/ui/header';
import Banner from '@/src/components/banner';
import Footer from '@/src/components/ui/footer';
import Newsletter from '@/src/components/newsletter';
const syne = Syne({
  subsets: ['latin'],
  variable: '--font-syne',
  display: 'swap',
});
const sansCjk = localFonts({
  src: '../../public/fonts/NotoSerifCJKtc-VF.otf',
  variable: '--font-sansCjk',
});
// const sansCjk = Noto_Sans_CJK({
//   subsets: ['latin'],
//   variable: '--font-cjk',
//   display: 'swap',
// });
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${syne.variable} ${sansCjk.variable} font-sans antialiased bg-white text-white tracking-tight`}
      >
        <div className='flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip'>
          <Header />
          {children}
          <Banner />
          <Newsletter />
          <Footer />
        </div>
      </body>
    </html>
  );
}
